<a href="https://colab.research.google.com/github/MegaBeing/MachineLearningJourneys/blob/main/00_TensorFlowIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Fundamentals😶‍🌫️😶‍🌫️😶‍🌫️
Let's cover: 
> 1. Intro to Tensors
2. Getting Info from Tensors
3. Manipulating Tensors
4. Tensors & Numpy
5. using @tf.functions ( a way to speed-up your basic python functions )
6. Using GPU with TensorFlow ( or TPUs )

In [ ]:
# import TensorFlow
import tensorflow as tf
tf.__version__

'2.9.2'

### Creating tensors using `tf.constant()`
creates an immutable tensor

In [ ]:
scalar = tf.constant(33)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=33>

In [ ]:
# check the number of dimensions
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of our vector
vector.ndim

1

In [ ]:
# create a matrix (basically has more than one dimension)
matrix = tf.constant([[10,10,10],[10,10,10],[10,10,10]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]], dtype=int32)>

In [ ]:
# check the dimension of our matrix
matrix.ndim

2

In [ ]:
# create a Tensor
tensor = tf.constant([[[1,2,3],[1,2,3],[1,2,3]],
                      [[1,2,3],[1,2,3],[1,2,3]],
                      [[1,2,3],[1,2,3],[1,2,3]]])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [ ]:
# check the dimension of tensor
tensor.ndim

3

### Creating tensors using `tf.Variable`
Basically it Creates a __mutable__ tensor

In [ ]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,10])

In [ ]:
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [ ]:
changable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
changable_tensor[0] = 7

TypeError: ignored

In [ ]:
# what if we use .assign()
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random tensors 


In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

In [ ]:
random_1,random_2,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###  Shuffling tensors

operational will give different shuffled data

In [ ]:
tf.random.shuffle(random_1,seed = 43) # operational level seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

Global will give same shuffled data

In [ ]:
tf.random.set_seed(43) # Global level seed
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

### Creating tensors using Numpy
Points of differences:  
 
  1. Tensors are more compatible with the GPUs than np_arrays
  2. Tensors are more easier to use with tensorflow functions than np_arrays
    
They have same format but uses may differ 

In [ ]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Conversion of np_array to **tensor**

In [ ]:
import numpy as np

In [ ]:
np_A = np.arange(1,25, dtype=np.int32)

np_A
# X = tf.constant(some_matrix) # capital for matrix or tensors
# y = tf.constant(vector) # non-capital for vectors


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tensor_a = tf.constant(np_A,shape=(2,3,4))
tensor_b = tf.constant(np_A)
(tensor_a ,tensor_b)

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Tensor Attributes
1. Shape
2. Size
3. Rank 
4. Axis or Dimension


In [ ]:
# shape
tensor_a.shape

TensorShape([2, 3, 4])

In [ ]:
# size
tf.size(tensor_a)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
tf.size(tensor_a).numpy()

24

In [ ]:
# Dimensions
tensor_a.ndim

3

In [ ]:
# dimension on specific access
tensor_a.shape[0]

2

### Indexing tensors
Just like python list

In [ ]:
tz = tf.zeros([4,3,2,3])
tz

<tf.Tensor: shape=(4, 3, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
# just like python list
tz[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.random.Generator.from_seed(42)
rank_2_tensor = rank_2_tensor.normal(shape=(3,2))
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# last item 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.06854702, -1.2573844 , -1.8107855 ], dtype=float32)>

In [ ]:
# add an extra dimension in the tensor
rank_2_tensor[...,tf.newaxis]

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]],

       [[-0.23193763],
        [-1.8107855 ]]], dtype=float32)>

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis = -1) # -1 means expand the final axis

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]],

       [[-0.23193763],
        [-1.8107855 ]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis = 0) # expand the 0th axis or 1st axis

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]]], dtype=float32)>

### Tensor Operations
'+' - addition  
'-' - subtraction   
'/' - division  
'*' - multiplication  

In [ ]:
t = tf.constant([10,7])
t +10

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 17], dtype=int32)>

In [ ]:
t*10

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([100,  70], dtype=int32)>

In [ ]:
t-10

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 0, -3], dtype=int32)>

In [ ]:
t/10

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1. , 0.7])>

In [ ]:
# we can also use built-in tensorflow functions

In [ ]:
tf.multiply(t,10, )

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([100,  70], dtype=int32)>

### Matrix Multiplication
One of the most common tensor operation

#### Straight multiplication

In [ ]:
t1 = tf.constant([[1,2],
                  [3,4]])
t2 = tf.constant([[5,6],
                  [7,8]])

In [ ]:
t1*t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

#### Dot Product

In [ ]:
# using matmul()
tf.matmul(t1,t2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [ ]:
# using python operator '@'
t1 @ t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [ ]:
# to reshape we can use 
# tf.reshape(tensor,shape=(bla))
ts = tf.ones(shape=(3,2))
tb = tf.reshape(ts,shape=(2,3))
ts.shape, tb.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# to transpose we can use 
# tf.transpose(tensor)
tc = tf.transpose(ts)
ts.shape,tc.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# using tf.tensordot()
tf.tensordot(tc,ts,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

### Change the Datatype of your tensor 

In [ ]:
B = tf.constant([3.4,7.8])
B.dtype

tf.float32

In [ ]:
C = tf.constant([1,2])
C.dtype

tf.int32

In [ ]:
# change from float32 to float16 (reduced precision)
D = tf.cast(B,dtype=tf.float16)
B.dtype, D.dtype

(tf.float32, tf.float16)

In [ ]:
# change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E.dtype, C.dtype

(tf.float32, tf.int32)

### Aggregating Tensors
Condensing the tensors from multiple values down to a smaller one

In [ ]:
D = tf.constant([-1,-2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>

In [ ]:
# absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

###### Forms of Aggregation
* Max
* Min
* Mean 
* Sum

In [ ]:
ten = tf.constant(np.random.randint(1,50,size=100))

In [ ]:
# max
tf.reduce_max(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
# min
tf.reduce_min(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# mean
tf.reduce_min(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# sum
tf.reduce_sum(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=2607>

In [ ]:
# variance
import tensorflow_probability as tfp
tfp.stats.variance(ten)

<tf.Tensor: shape=(), dtype=int64, numpy=227>

In [ ]:
# standard deviation
tf.math.reduce_std(tf.cast(ten,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=15.075977>

### Find the positional maximum and minimum

In [ ]:
# create a random tensor
tf.random.set_seed(42)
ele = tf.random.uniform(shape = [50])
ele

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(ele)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
ele[tf.argmax(ele)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(ele)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.argmin(ele)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
ele[tf.argmin(ele)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_min(ele)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a Tensor in one Dimension

In [ ]:
G = tf.constant(tf.random.normal(shape=[50]),shape = [1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[-0.55909735, -0.5347214 ,  2.3730333 , -1.5725931 ,
            0.8055056 , -0.83387697,  0.30611223,  2.2660494 ,
            0.2856414 , -1.5536156 ,  0.37975532,  0.76646256,
            0.3611479 ,  0.09653295,  0.2169556 , -0.81440705,
           -0.23623598,  0.49669704, -1.7737728 ,  0.20886712,
            1.0022159 , -0.12915266,  0.16589078,  0.4733353 ,
           -0.834051  ,  1.013081  ,  0.41076526,  0.5531745 ,
            1.7808596 , -0.3277541 ,  0.9474485 ,  0.9795105 ,
           -0.46425048,  1.3030936 , -0.24370237,  0.66929215,
            0.39855948, -2.4770668 , -0.3692293 , -0.8428784 ,
            1.8889831 , -0.6198924 ,  1.0777894 ,  1.0240268 ,
            0.26340935, -0.9011545 ,  0.8177133 , -0.27730602,
            1.1863395 , -0.11432811]]]]], dtype=float32)>

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([-0.55909735, -0.5347214 ,  2.3730333 , -1.5725931 ,  0.8055056 ,
       -0.83387697,  0.30611223,  2.2660494 ,  0.2856414 , -1.5536156 ,
        0.37975532,  0.76646256,  0.3611479 ,  0.09653295,  0.2169556 ,
       -0.81440705, -0.23623598,  0.49669704, -1.7737728 ,  0.20886712,
        1.0022159 , -0.12915266,  0.16589078,  0.4733353 , -0.834051  ,
        1.013081  ,  0.41076526,  0.5531745 ,  1.7808596 , -0.3277541 ,
        0.9474485 ,  0.9795105 , -0.46425048,  1.3030936 , -0.24370237,
        0.66929215,  0.39855948, -2.4770668 , -0.3692293 , -0.8428784 ,
        1.8889831 , -0.6198924 ,  1.0777894 ,  1.0240268 ,  0.26340935,
       -0.9011545 ,  0.8177133 , -0.27730602,  1.1863395 , -0.11432811],
      dtype=float32)>

### One Hot Encoding

In [ ]:
some_list = [0,1,2,3]
# using tf.one_hot()

tf.one_hot(some_list,depth=4)    #depth = no of parameters or cardilarity of resulting matrix

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values for one_hot encoding
tf.one_hot(some_list,depth=4,off_value='bad',on_value='good')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'good', b'bad', b'bad', b'bad'],
       [b'bad', b'good', b'bad', b'bad'],
       [b'bad', b'bad', b'good', b'bad'],
       [b'bad', b'bad', b'bad', b'good']], dtype=object)>

### Few commonly used math functions

In [ ]:
tensor = tf.range(1,10)
tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(tensor,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
tf.math.log(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensor and NumPy
They interact with each other very easily

In [ ]:
t = tf.constant(np.array([1,2,3]))
t

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [ ]:
np.array(t),type(np.array(t))

(array([1, 2, 3]), numpy.ndarray)

In [ ]:
t.numpy()[0]

1

In [ ]:
# though they have different datatypes
tensor_J = tf.constant([3.,7.,10.])
numpy_J = np.array([3.,7.,10.])
# let's check
tensor_J.dtype, numpy_J.dtype

(tf.float32, dtype('float64'))

### Finding access to GPU






 

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri Jan 13 09:18:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------