# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
one=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
two=np.array([[1,2],[3,4]])

# Create a 3-dimensional Numpy array using np.array()
three=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one.shape,one.ndim,one.dtype,type(one)

((3,), 1, dtype('int32'), numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
two.shape,two.ndim,two.dtype,type(two)

((2, 2), 2, dtype('int32'), numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
three.shape,three.ndim,three.dtype,type(three)

((3, 3, 3), 3, dtype('int32'), numpy.ndarray)

In [11]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data = pd.DataFrame(two,columns=["X","Y"])
data

X  Y
0  1  2
1  3  4

In [13]:
# Create an array of shape (10, 2) with only ones
onez=np.ones((10,2))
onez

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zero=np.zeros((7,2,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3
arr1=np.arange(0,100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr2=np.random.randint(0,10,size=(7,2))
arr2

array([[0, 6],
       [1, 3],
       [7, 8],
       [7, 8],
       [9, 1],
       [7, 7],
       [5, 8]])

In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr3=np.random.random(size=(3,5))
arr3

array([[0.59783047, 0.09514552, 0.22864849, 0.57639959, 0.43690955],
       [0.82131495, 0.7326221 , 0.73887634, 0.34681287, 0.14076239],
       [0.39624582, 0.23254807, 0.19078492, 0.89178557, 0.09672844]])

In [20]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr3=np.random.randint(0,10,size=(4,6))
arr3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

**Run the cell above again, what happens?**  
`ans:` The cell is giving the same random array  
**Are the numbers in the array different or the same? Why do think this is?**    
`ans:` They will be same as they are tied with numpy seed thus every time we run the cell it will give us the same array

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr4 = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(arr4)

In [26]:
arr4

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3],
       [1, 3, 5, 3, 1, 5, 7]])

In [23]:
# Find the 0'th index of the latest array you created
arr4[0]

array([7, 8, 3, 1, 4, 2, 8])

In [27]:
# Get the first 2 rows of latest array you created
arr4[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [28]:
# Get the first 2 values of the first 2 rows of the latest array
arr4[:2,:2]

array([[9, 7],
       [7, 8]])

In [29]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
onez=np.ones((3,5))
arr5=np.random.randint(0,10,size=(3,5))

In [30]:
# Add the two arrays together
onez+arr5

array([[ 7.,  9., 10., 10.,  3.],
       [ 7.,  1.,  4.,  4.,  5.],
       [ 7.,  7.,  4.,  7.,  3.]])

In [31]:
# Create another array of ones of shape (5, 3)
arr6=np.random.randint(0,10,size=(5,3))

In [33]:
# Try add the array of ones and the other most recent array together
onez+arr6

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

**When you try the last cell, it produces an error. Why do think this is?**  
`Ans:` Shape is different

How would you fix it?

In [34]:
arr6=arr6.reshape(3,5)

In [36]:
arr6+onez

array([[ 6.,  2., 10.,  9.,  5.],
       [ 6.,  4., 10.,  7.,  9.],
       [ 7.,  1.,  1.,  9.,  9.]])

In [37]:
# Create another array of ones of shape (3, 5)
onez

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
# Subtract the new array of ones from the other most recent array
arr6-onez

array([[ 4.,  0.,  8.,  7.,  3.],
       [ 4.,  2.,  8.,  5.,  7.],
       [ 5., -1., -1.,  7.,  7.]])

In [39]:
# Multiply the ones array with the latest array
arr6*onez

array([[5., 1., 9., 8., 4.],
       [5., 3., 9., 6., 8.],
       [6., 0., 0., 8., 8.]])

In [40]:
# Take the latest array to the power of 2 using '**'
arr6**2

array([[25,  1, 81, 64, 16],
       [25,  9, 81, 36, 64],
       [36,  0,  0, 64, 64]], dtype=int32)

In [41]:
# Do the same thing with np.square()
np.square(arr6)

array([[25,  1, 81, 64, 16],
       [25,  9, 81, 36, 64],
       [36,  0,  0, 64, 64]], dtype=int32)

In [42]:
# Find the mean of the latest array using np.mean()
np.mean(arr6)

5.333333333333333

In [43]:
# Find the maximum of the latest array using np.max()
np.max(arr6)

9

In [44]:
# Find the minimum of the latest array using np.min()
np.min(arr6)

0

In [45]:
# Find the standard deviation of the latest array
np.std(arr6)

3.0477678535099892

In [46]:
# Find the variance of the latest array
np.var(arr6)

9.288888888888888

In [47]:
# Reshape the latest array to (3, 5, 1)
arr6.reshape(3,5,1)

array([[[5],
        [1],
        [9],
        [8],
        [4]],

       [[5],
        [3],
        [9],
        [6],
        [8]],

       [[6],
        [0],
        [0],
        [8],
        [8]]])

In [48]:
# Transpose the latest array
arr6.T

array([[5, 5, 6],
       [1, 3, 0],
       [9, 9, 0],
       [8, 6, 8],
       [4, 8, 8]])

**What does the transpose do?**  
`Ans`: it changed the shape eventually just interchanging the elements of the tuple shape

In [49]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
mat1=np.random.randint(0,10,size=(3,3))
mat2=np.random.randint(0,10,size=(3,2))

In [50]:
# Perform a dot product on the two newest arrays you created
np.dot(mat1,mat2)

array([[ 76,  83],
       [ 96, 135],
       [ 44,  92]])

In [51]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
mat3=np.random.randint(0,10,size=(4,3))
mat4=np.random.randint(0,10,size=(4,3))

In [52]:
# Perform a dot product on the two newest arrays you created
np.dot(mat3,mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [53]:
mat3.shape,mat4.shape

((4, 3), (4, 3))

In [55]:
mat3=mat3.reshape((3,4))

In [57]:
mat3.shape,mat4.shape

((3, 4), (4, 3))

In [56]:
np.dot(mat3,mat4)

array([[18,  9, 39],
       [14, 32, 47],
       [18, 27, 52]])

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [59]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
mat3,mat4

(array([[3, 3, 0],
        [0, 6, 4],
        [0, 1, 0],
        [9, 2, 7]]),
 array([[0, 0, 1],
        [1, 5, 6],
        [4, 0, 0],
        [2, 1, 4]]))

In [60]:
# Compare the two arrays with '>'
mat3>mat4

array([[ True,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [61]:
# Compare the two arrays with '>='
mat3>=mat4

array([[ True,  True, False],
       [False,  True, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [62]:
# Find which elements of the first array are greater than 7
mat3>7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

In [63]:
# Which parts of each array are equal? (try using '==')
mat3==mat4

array([[False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False]])

In [64]:
# Sort one of the arrays you just created in ascending order
np.sort(mat3)

array([[0, 3, 3],
       [0, 4, 6],
       [0, 0, 1],
       [2, 7, 9]])

In [65]:
# Sort the indexes of one of the arrays you just created
np.argsort(mat3)

array([[2, 0, 1],
       [0, 2, 1],
       [0, 2, 1],
       [1, 2, 0]], dtype=int64)

In [66]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(mat3)

9

In [67]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(mat3)

2

In [68]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argsort(mat3,axis=1)

array([[2, 0, 1],
       [0, 2, 1],
       [0, 2, 1],
       [1, 2, 0]], dtype=int64)

In [69]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argsort(mat3,axis=0)

array([[1, 2, 0],
       [2, 3, 2],
       [0, 0, 1],
       [3, 1, 3]], dtype=int64)

In [70]:
# Create an array of normally distributed random numbers
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(0,100,10)

NameError: name 'np' is not defined

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.