# Numpy
* it is written in c, which is really fast language
* using this gives us great computational advantage

In [1]:
import numpy as np

## Datatypes & Attributes
* the main advantage of numpy is ndarray

### np.array([])
used to just make an array

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

### type()
gives the data type of the written array

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],
               [4,5,6]])
a2.shape

(2, 3)

In [5]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### np.shape
basically gives the shape _(a representation of dimensions in tuple form|)_ of the array  
For ex: a2(represented above) has __2 elements__ and those elements have __3 elements__  
thus it gives the output like this

In [6]:
a2.shape

(2, 3)

## np.ndim
used to give dimension of the particular array

In [7]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

* `a1` is a 1 dimensional array
* `a2` is a 2 dimensional array
* `a3` is a 3 dimensional array

## np.dtype
used to give the data type of the elements of the array

In [8]:
a1.dtype

dtype('int32')

## np.size
gives the number of elements in the array

In [9]:
a1.size

3

## example to show that numpy is the base of dataScience


In [10]:
import pandas as pd 
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## np.ones()
give the shape it will print the array(matrix) consisting only one as an element

In [11]:
ones = np.ones(shape=a2.shape)

In [12]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

## np.zeros()
this gives us an array having zeros as their element

In [13]:
zero = np.zeros(shape = a2.shape,dtype = int)

In [14]:
zero

array([[0, 0, 0],
       [0, 0, 0]])

## np.arange()
gives us the array within the range like we did in iteration

In [15]:
rAr = np.arange(0,11,2)
rAr

array([ 0,  2,  4,  6,  8, 10])

## np.random.randint(low,high,size=None)
gives array of specified size    
elements are between low and high which are specified by the programmer  
these elements are integers

In [16]:
ranAr = np.random.randint(0,10,size=a2.shape)
ranAr

array([[5, 4, 3],
       [7, 6, 0]])

## np.random.rand(shape)
this gives us the array in which we have random elements  
__Note__: Array shape must be specified

In [17]:
ran = np.random.rand(5,3)

In [18]:
ran

array([[0.5241294 , 0.96520616, 0.62710874],
       [0.33676199, 0.64345733, 0.24053159],
       [0.76610013, 0.86948032, 0.40330556],
       [0.44007642, 0.2124785 , 0.10377599],
       [0.67976684, 0.11761916, 0.96762166]])

## np.random.random()
* generates an array of specified size
* 0.0 <= element < 1.0

In [19]:
ranDom = np.random.random(a2.shape)
ranDom

array([[0.09936067, 0.16884093, 0.08181205],
       [0.65021893, 0.1212185 , 0.49666309]])

## np.random.seed(self,seed = None)
used to create constant random arrays  
written before any random function so that it can allign itself with the seed

In [20]:
np.random.seed(seed=7)
arr = np.random.randint(10,size = a2.shape)
arr
# no matter how many times you run the code you will get the same output

array([[4, 9, 6],
       [3, 3, 7]])

## np.linspace(`start`,`stop`,`num`)
Creates evenly spaced elements in np array so that the number of elements = num

In [21]:
x=np.linspace(0,10,100)
x

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

#### np.random.randn()
this gives us the values of any natural distribution curve

In [22]:
b=np.random.randn(1000)
b[:10]

array([-1.88022258, -0.43497813, -0.38546851, -0.22025144, -0.26946586,
       -0.04488102,  1.09512469,  0.08244521, -1.02327262, -1.61686249])

## Accessing the elements of the array

In [23]:
a1[0]
# 1D array

1

In [24]:
print(a2[1][1])
print(a2[1,1])
# 2D array

5
5


In [25]:
print(a3[0][1][2])
print(a3[0,1,2])
# 3D array

6
6


## slicing the Array

In [26]:
a3[0:1]
# the first one is included and the end one is excluded

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [27]:
a3 , a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [28]:
a3[:,:,:2]

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]]])

# Manupulating and comparing Arrays

## Arithmetic

In [29]:
ones = np.ones(shape=a1.shape , dtype=int)
ones,a1

(array([1, 1, 1]), array([1, 2, 3]))

### Addition

In [30]:
ones+a1

array([2, 3, 4])

### Subtraction

In [31]:
a1-ones

array([0, 1, 2])

### Multiplication
* it is not like normal matrix multiplication.  
* the smaller array is __*broadcasted*__ across the larger array so that they can have **compatible shapes**
* **Multiplication with constants**: same as in matrix


In [32]:
a1*ones

array([1, 2, 3])

In [33]:
a1*a2
# here as you can see a1 has been broadcasted over each element of a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [34]:
# here as you can see due to a2 shape we can't broadcast it onto a3
# to solve this we need to reshape it
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

### Division

In [ ]:
a3/a1

### Floor Division

In [ ]:
a3//a1

### Power


In [ ]:
a2**2

In [ ]:
a2**a1

### Function for Arithmetic operations
#### Square

In [ ]:
print(np.square(a1))

print(a1**2)

#### Add

In [ ]:
print(np.add(a1,ones))

print(a1+ones)

#### Modulus

In [ ]:
print(np.mod(a1,2))

print(a1 % 2)

## Aggregation
Performing same operation on a number of things

In [ ]:
listy = [1,2,3]
listy

In [ ]:
type(listy)

In [ ]:
# python sum
sum(listy)

In [ ]:
a1

In [ ]:
# numpy sum
np.sum(a1)

So the crux is that we should use **python sum** `sum()` when using _python Datatypes_ and  
use **NumPy sum** `np.sum()` when using _NumPy Datatypes_

#### Example

In [ ]:
Massive = np.random.random(100000)
Massive[:10]

In [ ]:
%timeit sum(Massive) # Python's sum()
%timeit np.sum(Massive) # Numpy's np.sum()

So as we can see that the `np.sum()` (NumPy) is way more faster than `sum()` (Python)

In [ ]:
a2

### Normal Math functions


In [ ]:
np.max(a2)  # Returns max value in the array

In [ ]:
np.min(a2)  # Returns min value in the array

In [ ]:
np.std(a2)  # Returns standard deviation of the array
# standard deviation = it is the measurement of how much the group of numbers are spread out from the mean

In [ ]:
np.var(a2)  # Returns variance of the array
# variance = measurement of average degree to which the number is different to the mean
# higher variance = higher range of numbers
# lower variance = lower range of numbers
# var = std**2

## Reshaping and Transposing
### Why do we __need__ it?
bcz of these broadcasting rules:  
Two dimensions are compatible when
* they are equal, or
* one of them is 1  
so these must be followed otherwise no arithmetic operation would work on those two arrays

In [ ]:
a2*a3

We got an error bcz they are not compatible with each other so we have to reshape the smaller array so that it can be easily when performing arithmetic operations

### reshape(`shape`)
used to reshape non compatible arrays so that we can perform arithmetic operations  
`Note` : number of elements in the array are __equal__ and also which is equal to the __product of the elements in the shape tuple__

In [ ]:
a2

In [ ]:
reshaped = a2.reshape(2,3,1)
reshaped

In [ ]:
a3

In [ ]:
reshaped*a3

### Transpose
you know what it is

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

## Dot Product
It is same as `matrix multiplication`

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(0,10,size=(5,3))
mat2 = np.random.randint(0,10,size=(5,3))

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
# Element-wise multiplication
mat1*mat2

In [ ]:
np.dot(mat1,mat2)

In [ ]:
mat2 = mat2.T

In [ ]:
mat2.shape, mat1.shape

In [ ]:
np.dot(mat2,mat1)

In [ ]:
random_array=np.dot(mat1,mat2)
random_array

In [ ]:
np.random.seed(1)
quan = np.random.randint(0,20,size=(5,3))
price = np.array([10,8,12])

In [ ]:
quan

In [ ]:
price

In [ ]:
price.shape, quan.shape

In [ ]:
tot = np.dot(price.T,quan.T)
tot

In [ ]:
tot.shape

In [ ]:
import pandas as pd
sales = pd.DataFrame(quan,index = ["Mon","Tue","Wed","Thu","Fri"],columns = ["Pasta","Maggi","Nacho"])
sales

In [ ]:
price_sales = pd.DataFrame(price.reshape(1,3),index=["Price"],columns=["Pasta","Maggi","Nacho"])
price_sales

In [ ]:
tot.shape

In [ ]:
sales["Total"]=tot

In [ ]:
sales

## Comparison operators
When we use **comparison operation** it actually compares each element `sequentially`

In [ ]:
a1

In [ ]:
a2

In [ ]:
a2>a1

So it compared `I1` of `a1` with `I11` of `a2` thus we are gettting `false`

In [ ]:
a1<a2

So we can do every operation we will get an array of **type**: `numpy.ndarray` with **dtype**: `bool`

## Sorting Arrays

In [ ]:
random_array

In [ ]:
random_array=np.delete(random_array,3,axis=0)

In [ ]:
random_array

### np.sort(array,axis=)

In [ ]:
np.sort(random_array,axis=1)

### np.argsort(`array`)
this function gives the index array which is used to sort the array

In [ ]:
random_array

In [ ]:
np.argsort(random_array)
#so as you can see 4 is on the first that means '15' should be on the first place 
# this is what array is trying to say 

### np.argmin(`array`,`axis=<int>`)
returns the index with minimum value

In [ ]:
random_array

In [ ]:
np.argmin(random_array,axis=0) ,np.argmin(random_array,axis=1)

`axis=0` means it will search row-wise that what will be the greatest  
`axis=1` means it will search column-wise that what will be the greatest

### np.argmax(`array`)
returns the index with max value

In [ ]:
np.argmax(random_array,axis=0),np.argmax(random_array,axis=1)

# practical example 
## NumPy in Action

![](panda.png)

### Turn the image into numbers

In [ ]:
from matplotlib.image import imread

In [ ]:
panda=imread("panda.png")
type(panda)

In [ ]:
panda.shape

In [ ]:
panda.size

In [ ]:
panda[:5]

what we did is that we actually converted each and every pixel of that image into the array

![](car-photo.png)

In [ ]:
carpng = imread("car-photo.png")
carpng